/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    WORKFLOWS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
workflow ingressFastqFiles {
    main:
        def runUID = generateUid( (('A'..'Z')+('a'..'z')+('0'..'9')).join(), 7 )
        def excludeList = ['fastq_fail', 'fail']
        def invalidParents = ['fastq', 'pass', 'fastq_pass', 'fastq_fail', 'fail', 'home']
       
        def read_pattern
        if (params.input_dir.toString().endsWith("/")) {
            read_pattern = "${params.input_dir}${params.read_pattern}"
        }
        else {
            read_pattern = "${params.input_dir}/${params.read_pattern}"
        }

        read_fastq = channel.fromPath(read_pattern, checkIfExists: true)
        read_fastq.dump(tag: "read_fastq_all")

        if (params.include_fastq_fail) {
            read_fastq = read_fastq
        }
        else {
            read_fastq = read_fastq.filter { 
                !(it.Parent.SimpleName in excludeList || it.Parent?.Parent.SimpleName in excludeList) 
            }
        }
        read_fastq.dump(tag: "read_fastq_no_fail")

        read_fastq = read_fastq.map { it ->
            def (barcode, sample_ID) = getValidParent(it.Parent, invalidParents)
            sample_ID = formatSampleId(sample_ID, barcode, runUID)
            tuple(sample_ID, it.simpleName, it)
            }
        
        read_fastq.dump(tag: "read_fastq_sample_tagged")
        read_fastq.dump(tag: "read_fastq")

    emit:
        read_fastq
}


/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PROCESSES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    FUNCTIONS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
def generateUid(String alphabet, int n) {
    // Generate a random UID of length n using the provided alphabet.
    (1..n).collect { alphabet[ new java.util.Random().nextInt( alphabet.length() ) ] }.join()
}

def getInvalidParents() {
    // Return a list of invalid parent directories
    ['fastq', 'pass', 'fastq_pass', 'fastq_fail', 'fail', 'home']
}

def getMinKnowBarcodeFolderPattern() {
    // Return the pattern for folder generated by MinKnow when doing barcode sequencing.
    // This is anonymous function is here to test its behavior in the getValidParent function, as we want to make sure that the barcode folders are correctly identified and ignored when looking for the sample ID.
    '^barcode\\d{2,3}$|unclassified'
}

def getMinKnowAutoRunFolderPattern() {
    // Return the pattern for folder generated by MinKnow for all sequence runs.
    '^\\d{8}_\\d{4}_.+'
}

def asPattern(patternLike) {
    if (patternLike instanceof java.util.regex.Pattern) {
        return patternLike
    }
    return java.util.regex.Pattern.compile(patternLike.toString())
}

def formatSampleId(String sample_ID, String barcode, String runUID) {
    // Format the sample ID by combining sample_ID, barcode, and runUID with optional param override
    // If params.sample_id is set, it overrides the sample_ID
    // Replaces whitespace with underscores and combines components with underscores
    
    if (params.sample_id != "") {
        sample_ID = params.sample_id.toString()
    }
    
    sample_ID = sample_ID.replaceAll("\\s+", "_")
    sample_ID = sample_ID + "_" + runUID
    
    if (barcode != "") {
        sample_ID = sample_ID + "_" + barcode
    }
    
    return sample_ID
}

def findValidParent(dir,
    invalidList=['fastq', 'pass', 'fastq_pass', 'fastq_fail', 'fail', 'home'],
    barcodePattern= "", 
    runFolderPattern= ""
    ) {
    /* Recursively find a valid parent directory path that is not in the invalid list and does not match the barcode or run folder patterns.
    
    The valid parent is normally the sample ID given in MinKnow
    A valid parent directory is defined as one that:
    - Is not in the invalidList
    - Does not match the barcodePattern
    - Does not match the runFolderPattern


    dir: {String} the current directory to check
    invalidList: {List} a list of directory names to ignore
    barcodePattern: {Pattern} a regex pattern to identify barcode folders, defaults to ONT barcode folders
    runFolderPattern: {Pattern} a regex pattern to identify run folders, defaults to MINKNOW run folder pattern    
    
    Returns:
    - The valid parent directory path, or / if no valid parent is found.
    */
    
    def folder_name = dir.simpleName
    if (barcodePattern == "") {
        barcodeRegex = asPattern(getMinKnowBarcodeFolderPattern())
    }
    else {
        barcodeRegex = asPattern(barcodePattern)
    }
    if (runFolderPattern == "") {
        runFolderRegex = asPattern(getMinKnowAutoRunFolderPattern())
    }
    else {
        runFolderRegex = asPattern(runFolderPattern)
    }


    def invalidFolderName = invalidList.contains(folder_name) || 
                     folder_name ==~ barcodeRegex || 
                     folder_name ==~ runFolderRegex
    
    // look one level up if current position is invalid, otherwise return current position
    if (invalidFolderName) {
        return findValidParent(dir.Parent, invalidList, barcodeRegex, runFolderRegex)
    }
    return dir
}

def getValidParent(dir,
    invalidList=['fastq', 'pass', 'fastq_pass', 'fastq_fail', 'fail', 'home'],
    barcodePattern= "",
    runFolderPattern= ""
    ) {
    /*
    get a sample and file id from a path

    dir: {String} the current directory to check
    invalidList: {List} a list of directory names to ignore
    barcodePattern: {Pattern} a regex pattern to identify barcode folders, defaults to ONT barcode folders
    runFolderPattern: {Pattern} a regex pattern to identify run folders, defaults to MINKNOW run folder pattern    
    
    Returns:
    sample_id
    file_id
    */
    
    def barcode = ""
    def barcodeRegex = (barcodePattern == "") ? asPattern(getMinKnowBarcodeFolderPattern()) : asPattern(barcodePattern)
    def runFolderRegex = (runFolderPattern == "") ? asPattern(getMinKnowAutoRunFolderPattern()) : asPattern(runFolderPattern)

    if (dir.simpleName ==~ barcodeRegex) {
        barcode = dir.simpleName
    }

    def validParent = findValidParent(dir, invalidList, barcodeRegex, runFolderRegex)
    
    return [barcode, validParent?.simpleName ?: ""]
}
