#!/usr/bin/env nextflow
/*
========================================================================================
    Workflow name
========================================================================================
    Github: https://github.com/cyclomics/wf-cyclomicsseq-amp
    Website: https://www.cyclomics.com/
----------------------------------------------------------------------------------------
*/

nextflow.preview.recursion = true

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT MODULES / PROCESSES / FUNCTIONS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
include { ingress_fastq_files } from './modules/ingress'
include {
    FilterShortReads;
    IndexReference;
    CountNumberOfReads;
    } from './modules/common'
include { generate_cycas_consensus } from './modules/consensus'
include {
    align_consensus_reads;
    merge_consensus_alignments;
    } from './modules/alignment'
include { call_variants } from './modules/variantcalling'
include {
    report_realtime;
    FinalizeReport
    } from './modules/report'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RUN MAIN WORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
workflow {
    assert params.input_dir : "--input_dir cannot be empty!"
    assert params.reference : "--reference cannot be empty!"

    def allowed_modes = ["map-ont", "sr"]
    assert params.minimap2?.mode in allowed_modes :
        "--minimap2.mode must be one of: ${allowed_modes.join(', ')}"

    def read_pattern = params.input_dir.endsWith("/")
            ? "${params.input_dir}${params.read_pattern}"
            : "${params.input_dir}/${params.read_pattern}"
        
    def stop_pattern = params.input_dir.endsWith("/")
        ? "${params.input_dir}${params.stop_pattern}"
        : "${params.input_dir}/${params.stop_pattern}"

    def ch_reference = IndexReference(channel.fromPath(params.reference)).collect()
    def minimap2_mode = params.minimap2.mode

    if (params.regions != "auto") {
        ch_regions = channel.value(file(params.regions))
    } else {
        log.info "Regions of interest will be detected automatically"
        ch_regions = channel.value("auto")
    }

    // Start ingress workflow
    ingress_fastq_files(read_pattern, stop_pattern)
    raw_fastq = ingress_fastq_files.out.read_fastq
    raw_fastq_json = CountNumberOfReads(raw_fastq, 'raw')

    // 1. Filter & QC
    FilterShortReads(raw_fastq)
    // TODO: Count number of filtered reads

    // 2. Consensus
    generate_cycas_consensus(FilterShortReads.out, ch_reference)
    consensus_fastq = generate_cycas_consensus.out.fastq
    consensus_json = generate_cycas_consensus.out.json
    // TODO: Use plots generated by Cycas

    // 3. Alignment
    align_consensus_reads(consensus_fastq, consensus_json, ch_reference, minimap2_mode, ch_regions)
    annotated_bam = align_consensus_reads.out.annotated_bam
    depth_table = align_consensus_reads.out.depth_table

    // REPORT: Real-time
    report_realtime(
        raw_fastq_json,
        depth_table,  // channel.empty() if regions == 'auto'
    )

    // We require that all previous processes finish before continuing analysis.
    // groupTuple() controls this behaviour, since it collects all upstream channels.
    // 4. Merge all alignments
    grouped_annotated_bam = annotated_bam
            .groupTuple(by: 0)
            .map { it -> tuple(it[0], it[1], it[2]) }
    merge_consensus_alignments(grouped_annotated_bam, ch_regions)
    merged_bam = merge_consensus_alignments.out.merged_bam
    regions = merge_consensus_alignments.out.regions
    
    // 5. Variant calling
    call_variants(merged_bam, regions, ch_reference)

    // REPORT: Final
    // TODO: This will also take the output of any post-merge analyses
    FinalizeReport(
        report_realtime.out.realtime_report.last().combine(
            call_variants.out.variant_table, by: 0
        )
    )
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
